#%RAML 1.0
title: small-api
mediaType: 
- application/json
version: v1.0.1

/buy:
  get:
    body:
      application/json:
        example:
          {
            "status": "hitted service"
          }